// Errors
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// Users
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT'
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const FAILURE_REGISTER = 'FAILURE_REGISTER'
export const UPDATE_USER = 'UPDATE_USER'
export const SUCCESS_UPDATE_USER = 'UPDATE_USER_SUCCESS'
export const FAILURE_UPDATE_USER = 'FAILURE_UPDATE_USER'
